### ISSUE TITLE
Maps don't work, Kibana update needed

### ISSUE THREAD

**Issue by edjez** [instedd/telemetry_rails#127] opened 2016-07-20 07:37 UTC
Maps look like this- 
![image](https://cloud.githubusercontent.com/assets/1182549/16978683/08804ce2-4e12-11e6-9f2a-fc69b2482701.png)
There's a fix it seems in a recent update or hotfix, pls look at 
https://github.com/elastic/kibana/issues/7717

**Comment by nditada** [comment] 2016-07-20 12:41
duplicate of #112

**Closed as completed by nditada** 2016-07-20 12:41 UTC
